- name: setting up apache webserver
  hosts: Amazon-Clients

  tasks:
    - name: update all packages
      ansible.builtin.yum:
        name: '*'
        state: latest
    - name: Install Apache
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: Start service httpd, if not started
      ansible.builtin.services:
        name: httpd
        state: started
    - name: Start service httpd on boot
      ansible.builtin.services:
        name: httpd
        enabled: true
    - name: Copy index.html file from the controller to the target hosts
      ansible.builtin.copy:
        src: /home/ubuntu/index.html
        dest: /var/www/html